RedHatInsights/catalog_inventory-api

app/controllers/api/v1/tasks_controller.rb
app/models/source.rb
db/migrate/20201208185240_change_refresh_status_to_source.rb
db/schema.rb
public/doc/openapi-3-v1.0.json
public/doc/openapi-3-v2.0.json
public/doc/openapi-3-v3.0.json
spec/controllers/api/v1x0/tasks_controller_spec.rb

Changed source and task schema

---

config/initializers/ingress_listener.rb
lib/ingress_listener.rb
lib/kafka_listener.rb
spec/lib/kafka_listener_spec.rb

To implement and enable a working listener create a script file under `config/initializers` and implement a subclass of `KafkaListener`

Add base kafka_listener and configure one example for ingress events

---

db/migrate/20201222201453_add_attributes_to_sources.rb
db/schema.rb
public/doc/openapi-3-v3.0.json

https://github.com/RedHatInsights/catalog_inventory-api/issues/10

Add more attributes to sources

---

app/services/post_check_availability_task_service.rb
public/doc/openapi-3-v3.0.json

Update three attributes: `last_checked_at`, `last_available_at` and `availability_status` of `Source` based on the task result

update Source with more information

---

app/models/incremental_refresh_persister_task.rb
app/models/launch_job_task.rb
app/models/mqtt_client_task.rb
app/services/check_availability_task_service.rb
app/services/endpoint_create_task_service.rb
app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb
app/services/launch_job_task_service.rb
app/services/mqtt_controller_service.rb
app/services/persister_task_service.rb
app/services/post_check_availability_task_service.rb
app/services/post_launch_job_task_service.rb
app/services/post_persister_task_service.rb
app/services/source_create_task_service.rb
app/services/source_destroy_task_service.rb
app/services/task_service.rb
lib/events/event_router.rb
lib/events/ingress_listener.rb
lib/events/source_listener.rb
lib/events/tower_operation_listener.rb
spec/services/mqtt_controller_service_spec.rb
spec/services/source_create_task_service_spec.rb
spec/services/source_destroy_task_service_spec.rb

This PR contains:
1. add validation logic on input options in service class;
2. add missing spec files

Add logic to validate input options and spec files

---

Gemfile
app/services/incremental_refresh_upload_task_service.rb
app/services/mqtt_controller_service.rb

Also ran into a commit issue we have to force a commit when we
create a new record in a separate thread

Use paho-mqtt gem temporarily till we get cloud controller

---

app/services/source_create_task_service.rb
spec/services/source_create_task_service_spec.rb

There is no tenant method we have to access the Tenant object by external_account number

Fixed error locating Tenant object

---

lib/events/kafka_listener.rb
lib/headers/service.rb
lib/sources/service.rb

Extract different header creation into a `Headers::Service`

Introduce Header::Service to create all kinds of user headers

---

app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb

This allows us to expect the data in the same order everytime from
the tower

Add order=id in Ansible Tower Requests

---

app/services/incremental_refresh_upload_task_service.rb

Removed an extra ?

---

app/services/post_check_availability_task_service.rb

The Sources API is expecting the data to be in JSON format for
the availability message

Convert the payload to JSON before we send it to Kafka

---

app/controllers/api/v1x0/tasks_controller.rb
app/models/launch_job_task.rb
spec/controllers/api/v1x0/tasks_controller_spec.rb

We dont have to publish it from the service

The task_controller publishes kafka messages

---

config/initializers/tower_operation_listener.rb
lib/events/tower_operation_listener.rb

Not sure how these got deleted the operations worker was no longer
running

Added the operations listener

---

app/services/launch_job_task_service.rb
spec/services/launch_job_task_service_spec.rb

When launching a Job Template the URL is
https://tower/api/v2/job_templates/12/launch/
When launching a workflow the URL is
https://tower/api/v2/workflow_job_templates/12/

A different URL for Workflows

---

db/migrate/20210206152407_change_index_on_tags.rb
db/schema.rb

https://github.com/RedHatInsights/catalog_inventory-api/issues/59

Changed index on tags

---

app/controllers/api/v1x0/sources_controller.rb
app/models/mqtt_client_task.rb
app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb
app/services/persister_task_service.rb
app/services/post_check_availability_task_service.rb
app/services/post_persister_task_service.rb
app/services/source_refresh_service.rb
config/routes.rb
db/migrate/20210208200543_add_child_task_it_on_tasks.rb
db/schema.rb
lib/catalog_inventory/api/body_parse_error.rb
lib/catalog_inventory/api/exception.rb
lib/catalog_inventory/exceptions.rb
public/doc/openapi-3-v1.0.json

Added `/sources/:id/refresh` endpoint to support refresh logic

Add logic to support refresh endpoint

---

app/services/post_persister_task_service.rb
spec/services/post_persister_task_service_spec.rb

Allow the UI to show the last refresh stats about how many objects
were added, updated, deleted.

Formatting of last refresh message

---

app/services/mqtt_controller_service.rb

https://issues.redhat.com/browse/SSP-2131

Send forwardable headers to cloud controller

---

app/services/mqtt_controller_service.rb
db/migrate/20210215152445_add_message_id_on_tasks.rb
db/schema.rb
public/doc/openapi-3-v1.0.json

https://issues.redhat.com/browse/SSP-2130

Added message id in tasks record

---

app/models/source.rb
app/services/check_availability_task_service.rb
app/services/endpoint_create_task_service.rb
app/services/full_refresh_upload_task_service.rb
app/services/persister_task_service.rb
app/services/task_service.rb

https://issues.redhat.com/browse/SSP-2135

add availability check after source is ready

---

public/doc/openapi-3-v1.0.json

Update title and description for the MQttClientId

Update title and description for the MQttClientId

---

app/controllers/api/v1x0/tasks_controller.rb

fixes https://issues.redhat.com/browse/SSP-2139

Publish kafka events with stored forwardable_headers

---

app/services/post_check_availability_task_service.rb
db/migrate/20210218190445_add_availability_check_message_to_sources.rb
db/schema.rb
public/doc/openapi-3-v1.0.json
spec/services/post_check_availability_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2137

Add availability message to source

---

Gemfile
app/models/task.rb
app/services/source_refresh_service.rb
config/initializers/clowder_config.rb
public/doc/openapi-3-v1.0.json
spec/models/task_spec.rb

https://issues.redhat.com/browse/SSP-2133

Add refresh time interval if task is timed out

---

app/services/post_persister_task_service.rb
spec/services/post_persister_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2128

Fixed to send SHA and size from refresh tasks

---

public/doc/openapi-3-v1.0.json

Added a space between Availability Message

---

app/models/launch_job_task.rb
spec/controllers/api/v1x0/tasks_controller_spec.rb
spec/models/launch_job_task_spec.rb

https://issues.redhat.com/browse/SSP-2136

Set launch job task failed by checking its output status

---

lib/events/kafka_listener.rb

https://issues.redhat.com/browse/SSP-2140

Changed x-rh-insights-request-id with meaningful content

---

app/models/source.rb

https://issues.redhat.com/browse/SSP-2138

Add destroy dependent for tasks and service offerings in source

---

app/controllers/api/v1x0/tasks_controller.rb
app/models/launch_job_task.rb
app/models/towing_task.rb
app/services/post_launch_job_task_service.rb
spec/controllers/api/v1x0/tasks_controller_spec.rb
spec/models/launch_job_task_spec.rb
spec/services/towing_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2144

Refactor sending Kafka messages for launch task completed

---

app/models/launch_job_task.rb
app/services/check_availability_task_service.rb

https://issues.redhat.com/browse/SSP-2144

Added missing info in the Kafka payload

---

app/models/towing_task.rb

https://issues.redhat.com/browse/SSP-2144

Overwrite super hook in child class

---

Gemfile
app/models/check_availability_task.rb
app/models/cloud_connector_task.rb
app/models/full_refresh_upload_task.rb
app/models/incremental_refresh_upload_task.rb
app/models/launch_job_task.rb
app/models/mqtt_client_task.rb
app/models/source.rb
app/services/check_availability_task_service.rb
app/services/cloud_connector_service.rb
app/services/endpoint_create_task_service.rb
app/services/mqtt_controller_service.rb
config/initializers/clowder_config.rb
db/migrate/20210302144831_rename_mqtt_client_id_on_sources.rb
db/schema.rb
deploy/clowdapp.yaml
public/doc/openapi-3-v1.0.json
spec/services/check_availability_task_service_spec.rb
spec/services/cloud_connector_service_spec.rb
spec/services/endpoint_create_service_spec.rb
spec/services/mqtt_controller_service_spec.rb
spec/services/towing_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2134

Changed MQTT to cloud connector

---

Dockerfile
deploy/clowdapp.yaml
docker-assets/entrypoint
docker-assets/run_rails_server

Replaces #98 
This helps to boot up the pod in clowder. A follow-up PR will correct the kafka topic names.

Revise clowdapp.yaml to work in clowder

---

Gemfile
db/migrate/20210310203929_remove_unused_sources_attributes.rb
db/schema.rb
public/doc/openapi-3-v1.0.json

Remove leftover `bytes_received` and `bytes_sent` from `sources`
https://issues.redhat.com/browse/SSP-2162

Remove unused sources attributes

---

cdappconfig.json
config/initializers/clowder_config.rb
lib/events/ingress_listener.rb
lib/events/source_listener.rb
lib/events/tower_operation_listener.rb

A follow-up of #99 to get correct topic name.

Use topics from ClowderConfig

---

app/models/check_availability_task.rb
app/models/full_refresh_upload_task.rb
app/models/incremental_refresh_upload_task.rb
app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb

Add `Message sent to RHC #{controller_message_id}` to CheckAvailabiltyTask when connect with connector.

update availability message for CheckAvailabilityTask

---

build_deploy.sh
deploy/clowdapp.yaml

1. create quay :latest tag for image
2. temp add `sources_url` back in env to let pod alive

Add latest tag to quay image

---

app/models/check_availability_task.rb
app/models/full_refresh_upload_task.rb
app/models/incremental_refresh_upload_task.rb

Hope this can solve the issue, return `availability_message` with `controller_message_id`

Replace debug message with reload

---

bin/cleanup_tasks
config/initializers/ingress_listener.rb
config/initializers/init_listeners.rb
config/initializers/init_types_envs.rb
config/initializers/source_listener.rb
config/initializers/tower_operation_listener.rb
deploy/clowdapp.yaml

Add a cronjob pod to cleanup older tasks

Add scheduled pod to cleanup tasks

---

app/services/post_persister_task_service.rb
app/services/source_refresh_service.rb
spec/services/post_persister_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2189

Temp remove incremental refresh on source object

---

db/migrate/20210407123702_add_source_updated_at_attribs.rb
db/schema.rb

https://issues.redhat.com/browse/SSP-2191

Add missing source_updated_at attribute to some tower objects

---

app/services/cloud_connector_service.rb
config/initializers/clowder_config.rb
deploy/clowdapp.yaml

https://issues.redhat.com/browse/SSP-2190

Add PSK support for cloud controller service

---

config/routes.rb
public/doc/openapi-3-v1.0.json
spec/requests/api/v1.0/service_instances_spec.rb
spec/requests/api/v1.0/service_offering_nodes_spec.rb
spec/requests/api/v1.0/service_offerings_spec.rb

https://issues.redhat.com/browse/SSP-2174

Remove service credentials endpoints for instance and offering objects

---

Dockerfile
deploy/clowdapp.yaml
docker-assets/entrypoint

This will help the app to run in stage with RDS.

Use RDS with root CA

---

app/controllers/api/v1x0/tasks_controller.rb
app/models/task.rb
config/routes.rb
public/doc/openapi-3-v1.0.json
spec/requests/api/v1.0/sources_spec.rb
spec/requests/api/v1.0/tasks_spec.rb

https://issues.redhat.com/browse/SSP-2221

Add endpoint to list tasks for the source

---

app/models/check_availability_task.rb
app/models/concerns/owner_field.rb
app/models/task.rb
db/migrate/20210430131022_drop_service_offering_icons.rb
db/migrate/20210430145850_add_owner_on_tasks.rb
db/schema.rb
public/doc/openapi-3-v1.0.json
spec/controllers/api/v1x0/tasks_controller_spec.rb
spec/factories/tasks.rb
spec/models/task_spec.rb
spec/requests/api/v1.0/filter_spec.rb
spec/requests/api/v1.0/tasks_spec.rb
spec/services/check_availability_task_service_spec.rb

https://issues.redhat.com/browse/SSP-2227

Add owner to Tasks

---

Dockerfile
config/application.rb
config/clowder_config.rb
docker-assets/entrypoint

This PR changes:
1. Use `before_intialize` to make sure `ClowdConfig` is set in the beginning;
2. Change `entrypoint` to totally depend on `ClowdConfig`;

Use before_initialize and change entrypoint to depend on ClowdConfig

---

app/controllers/api/v1x0/sources_controller.rb
app/services/source_refresh_service.rb
config/routes.rb
public/doc/openapi-3-v1.0.json
spec/controllers/api/v1x0/sources_controller_spec.rb

https://issues.redhat.com/browse/SSP-2197

Add sources/:id/incremental_refresh endpoint

---

lib/events/kafka_listener.rb

https://issues.redhat.com/browse/SSP-2246

Wrap all DB commands within connection_pool

---

lib/events/kafka_listener.rb

https://issues.redhat.com/browse/SSP-2247

Only parse if the payload is string

---

app/models/check_availability_task.rb
app/models/full_refresh_persister_task.rb
app/models/full_refresh_upload_task.rb
app/models/incremental_refresh_persister_task.rb
app/models/incremental_refresh_upload_task.rb
app/services/check_availability_task_service.rb
spec/models/check_availability_task_spec.rb

https://issues.redhat.com/browse/SSP-2241

Replace after_update with after_commit

---

app/models/check_availability_task.rb
app/models/full_refresh_persister_task.rb
app/models/full_refresh_upload_task.rb
app/models/incremental_refresh_persister_task.rb
app/models/incremental_refresh_upload_task.rb
app/models/launch_job_task.rb
app/models/source.rb
app/models/task.rb
app/models/towing_task.rb
app/services/check_availability_task_service.rb
app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb
app/services/launch_job_task_service.rb
app/services/persister_task_service.rb
app/services/post_launch_job_task_service.rb
app/services/source_create_task_service.rb
spec/models/launch_job_task_spec.rb

https://issues.redhat.com/browse/SSP-2241

Replace all after_update with after_update_commit
