app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb

The inventory attribute was being used twice in the job_template and workflow_template calls

Removed duplicate inventory attribute

---

app/services/application_task_service.rb
app/services/check_availability_task_service.rb
app/services/full_refresh_upload_task_service.rb
app/services/persister_task_service.rb
app/services/source_create_task_service.rb
app/services/source_destroy_task_service.rb
app/services/task_service.rb
config/initializers/init_types_envs.rb
config/initializers/load_extensions.rb
config/initializers/sources_api.rb
db/migrate/20210107222354_add_enabled_to_sources.rb
db/schema.rb
lib/events/event_router.rb
lib/sources/service.rb
public/doc/openapi-3-v3.0.json
spec/services/check_availability_task_service_spec.rb
spec/services/full_refresh_upload_task_service_spec.rb
spec/services/source_create_task_service_spec.rb
spec/services/source_destroy_task_service_spec.rb

This PR contains changes:
1. when service starts, retrieve `source_type_id` and `application_type_id` from Sources service and store them in environment variables: ENV["SOURCE_TYPE_ID"] and ENV["APPLICATION_TYPE_ID"];
2. Only those `Source.create` or `Source.destroy` KAFKA messages with matching `source_type_id` are processed;
3. Only those `Application.create` or `Application.destroy` Kafka messages with matching `application_type_id` are processed;
4. `enabled` attribute is added to `Source` object, default is `false`. It will change to `true` when receiving `Application.create` message, and change to `false` when  `Application.destroy` is received.
5. The check_availability_task, upload_task and persister_task only triggers when its source is enabled. …

Add source enabled check

---

db/migrate/20210119183553_remove_resource_time_columns.rb
db/schema.rb

Removed unused attributes: `resource_timestamp`, `resource_timestamps` and `resource_timestamps_max`

remove unused attributes from tables

---

app/services/task_service.rb

Removed the check on `external_tenant` of input options

Fix validate_options in task service

---

Gemfile
app/services/mqtt_controller_service.rb

This is temporary till we dock with Cloud Controller
Sample URL
**MQTT_CLIENT_URL=mqtts://ssl_broker:443**

Support for SSL based MQTT

---

app/services/check_availability_task_service.rb
app/services/full_refresh_upload_task_service.rb
app/services/launch_job_task_service.rb
app/services/persister_task_service.rb
app/services/post_launch_job_task_service.rb
app/services/source_create_task_service.rb

When running in a multi threaded process the transactions needs to
be committed so that other threads can see it, otherwise the other
threads or pocesses wont have visibility to these newly created
objects

Commit the records into the DB

---

app/services/source_create_task_service.rb
app/services/source_destroy_task_service.rb
spec/services/source_create_task_service_spec.rb
spec/services/source_destroy_task_service_spec.rb

The Kafka Message when a Source is added has id e.g.
```
{"@timestamp":"2021-01-22T22:42:32.921945 ","hostname":"catalog-inventory-api-9-8flnq","pid":86,"tid":"2b01edd55498","level":"info","message":"Kafka message Source.create received with payload: {\"id\"=\u003e19780, \"name\"=\u003e\"Slate Rock and Gravel Company\", \"uid\"=\u003e\"5699ca7a-58b6-4bf8-8a54-54e2b7318199\", \"created_at\"=\u003e\"2021-01-22 22:42:32 UTC\", \"updated_at\"=\u003e\"2021-01-22 22:42:32 UTC\", \"source_type_id\"=\u003e3, \"version\"=\u003enil, \"availability_status\"=\u003enil, \"imported\"=\u003enil, \"source_ref\"=\u003e\"Yabba_Dabba_Doo\", \"last_checked_at\"=\u003enil, \"last_available_at\"=\u003enil, \"tenant\"=\u003e\"6089719\"}"}
```

Source_id should be id when adding/destroying a source

---

app/services/source_create_task_service.rb
spec/services/source_create_task_service_spec.rb

When we get the Source Object from Kafka it preserves the source_type_id
as integer, while the same source_type objects id attribute is converted
to string before being sent out via the Rest API.

Source Type ID coming back is a string and not int

---

app/services/source_create_task_service.rb
spec/services/source_create_task_service_spec.rb

The tenant is set from the Kafka Message headers and need not be
set from the incoming message payload section

Fixed the specs to use acts_as_tenant which is set from headers

---

app/services/source_create_task_service.rb
spec/services/source_create_task_service_spec.rb

The types needed to be int instead of string when handling Kafka payload
source_uid should have been uid

Fixed types added name to source

---

app/services/check_availability_task_service.rb
lib/events/kafka_listener.rb
spec/services/check_availability_task_service_spec.rb

The Check Availability message doesn't have any headers so we have to fabricate one from external_tenant

Check Availability Message has no headers

---

app/services/source_create_task_service.rb
app/services/source_destroy_task_service.rb
config/initializers/init_types_envs.rb
spec/services/source_create_task_service_spec.rb
spec/services/source_destroy_task_service_spec.rb

The ID's that we get from REST API is string but the ones that
we get from Kafka message are integer's. Since most of the back end
processing we do is based on Kafka messages leave the ID's as integers

Leave ID's as integer

---

app/services/application_task_service.rb

It doesn't make sense to be converting the id to string every time before comparison. We convert the id that we fetch via the REST API from a string to int and when we do the comparison here we do int comparison

The Application ID is a integer field dont convert to string

---

app/services/check_availability_task_service.rb
app/services/task_service.rb
lib/sources/service.rb
spec/services/check_availability_task_service_spec.rb

In the case of multiple pods runs in the same time, the events of `source.create`, `endpoint.create`, `application.create`, and `check_availability` may be consumed by different pods. So before check_availability starts, check with source API to see its latest status

Refresh the source if it is not ready for availability check

---

app/services/full_refresh_upload_task_service.rb
app/services/incremental_refresh_upload_task_service.rb
app/services/post_persister_task_service.rb

Set `refresh_started_at` when Upload Task is created.
Set `refresh_finished_at` when Persister Task is complete.

Update source refresh start and finish accordingly

---

app/services/mqtt_controller_service.rb
spec/services/mqtt_controller_service_spec.rb

If the RHCD running on prem can't be reached or the Cloud
Controller itself can't be reached or for any other errors we have
to mark the task as Failed.

Update the Task object if we get error from Cloud Controller

---

Gemfile
config/environment.rb
config/initializers/clowder_config.rb
spec/rails_helper.rb

The app-common-ruby gem has been changed to depend on a single environment variable to check if Clowder Config has been enabled.

Remove ACG_CONFIG env variable

---

app/services/mqtt_controller_service.rb

We were using a temporary account number till the Cloud Controller
team finished their work on account numbers.

Removed the temporary account number

---

app/models/source.rb
spec/models/source_spec.rb

Remove the dependency on Kafka messages when starting `CheckAvailabilityTask`
https://issues.redhat.com/browse/SSP-2178

Triggers CheckAvailabilityTask no matter which Kafka messages come first

---

deploy/clowdapp.yaml

Temp changed dependencies into optional to diagnose the clowder deployment issue

Change dependencies to optional

---

app/controllers/api/v1x0/sources_controller.rb
spec/controllers/api/v1x0/sources_controller_spec.rb

https://issues.redhat.com/browse/SSP-2187
If a Source is not Available we should run the Check Availability and if the Source is Available at the tail end of the Check Availability it will kick off a Refresh

Change source refresh based on its availability status

---

app/services/post_persister_task_service.rb
spec/services/post_persister_task_service_spec.rb

The changes in https://github.com/RedHatInsights/catalog_tower_persister/pull/44 populate `last_refresh_message` with modified data. Update it to Source object.

Get back last_refresh_message in Source

---

pr_check.sh

We are switching to use absolute dir paths to avoid confusion
Also, I incorporated your quay LABEL approach into the common build.sh: https://github.com/RedHatInsights/bonfire/blob/master/cicd/build.sh#L32

Updates to pr_check.sh

---

deploy/clowdapp.yaml

The name has to match secret in openshift which does not allow underscore.

change database name to catalong-inventory in clouwadd.yaml

---

deploy/clowdapp.yaml

so that we can distinguish the two services with different ports

rename the deployment to api-v2

---

config/initializers/clowder_config.rb
deploy/clowdapp.yaml

3Scale team has changed the port number from 8080 to 8000. No need to have an extra service to do the switch work. 
https://issues.redhat.com/browse/RHCLOUD-13889

Remove the extra service to route port number

---

app/models/application_record.rb
spec/requests/api/v1.0/tasks_spec.rb

By default the inherit column in STI does not appear in JSON output. But we need this information to tell us the task type. This PR adds it.

Add STI task type in json output

---

app/models/incremental_refresh_upload_task.rb

Fix to add `ok` in the status list to trigger callback service.
https://issues.redhat.com/browse/SSP-2354

Fix source refresh failure in callback method
